theme: jekyll-theme-minimal
title: JP Chavat | Senior Engineer (MSc) with an eye for Economics 
description: Exploring the intersection of tech, economics, and real-world problem-solving. Let's connect!
author: JP Chavat
expertise: 
  - Backend Engineering 
  - Software Development 
  - Data-driven solutions
  - Economic Modeling
