# Site settings
# These personalize your site. Access them in HTML via {{ site.title }}, {{ site.email }}, etc.

theme: minima 
title: JP Chavat
description: Senior Backend Engineer (MSc) exploring the intersection of data analysis, economic modeling, and tech-driven problem-solving (with a touch of personal perspective). Let's connect! 
author: JP Chavat
# google_analytics: G-MPHEXVJPPH # Your actual Google Analytics Tracking ID

# Contact & Social
email: hey@jpchavat.com  
baseurl: ""              # Only if your site is in a subdirectory
url: "https://jpchavat.com" 
twitter_username: jpchavat
github_username: jpchavat
linkedin_username: jpchavat

# Future-proofing for content organization 
collections:
  blog:
    output: true  
  projects: 
    output: true
